# Generated by Django 3.2.4 on 2021-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, to='brand.BrandCategory', verbose_name='Категории'),
        ),
    ]
