# Generated by Django 3.2.4 on 2021-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Порядок вывода')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Глобальная категория бренда')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('brands', models.ManyToManyField(blank=True, to='brand.Brand', verbose_name='Бренды')),
            ],
            options={
                'verbose_name': 'Глобальная категория',
                'verbose_name_plural': 'Глобальные категория',
            },
        ),
    ]
