# Generated by Django 3.2.4 on 2021-06-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brandglobalcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Порядок вывода')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название линейки товаров')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Название линейки товаров',
                'verbose_name_plural': 'Названия линеек товаров',
            },
        ),
    ]
