# Generated by Django 3.2.4 on 2021-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_banner_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order_num',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'verbose_name': 'Линейка товаров по категориям', 'verbose_name_plural': 'Линейки товаров по категориям'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('order_num',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео на главной'},
        ),
        migrations.AddField(
            model_name='brand',
            name='cat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, to='brand.BrandCategory', verbose_name='Линейка товаров по категориям'),
        ),
    ]
