# Generated by Django 3.2.4 on 2021-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20210628_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingredient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='brandingredient',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='brandvideo',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код видео'),
        ),
    ]
