# Generated by Django 3.2.4 on 2021-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20210628_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to='brand/ingridient/', verbose_name='Кртинка'),
        ),
    ]
