# Generated by Django 3.2.4 on 2021-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_remove_brandpress_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Порядок вывода')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/video/', verbose_name='Логотип ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/video/', verbose_name='Картинка ')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('text', models.CharField(blank=True, max_length=230, null=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'Элемент блока пресса',
                'verbose_name_plural': 'Элементы блока пресса',
            },
        ),
        migrations.CreateModel(
            name='PressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Порядок вывода')),
                ('name', models.CharField(blank=True, max_length=230, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория блока прессы',
                'verbose_name_plural': 'Категории блока прессы',
            },
        ),
    ]
