# Generated by Django 3.2.4 on 2021-07-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_press_presscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='is_active',
        ),
        migrations.AddField(
            model_name='press',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='brand.presscategory', verbose_name='Бренд'),
        ),
    ]
