# Generated by Django 3.2.4 on 2021-07-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_auto_20210701_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='press',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='brand.presscategory', verbose_name='Категория'),
        ),
    ]
