# Generated by Django 3.2.4 on 2021-06-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара')),
                ('name_lower', models.CharField(blank=True, default='', editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена')),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('image', models.ImageField(blank=True, upload_to='images/catalog/items/', verbose_name='Изображение товара')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Отображать товар ?')),
                ('is_present', models.BooleanField(db_index=True, default=True, verbose_name='Товар в наличии ?')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Товар новинка ?')),
                ('is_bestseller', models.BooleanField(db_index=True, default=False, verbose_name='Товар новинка ?')),
                ('buys', models.IntegerField(default=0, editable=False)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_items', to='brand.brand', verbose_name='Бренд')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='brand.brandcategory', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Tовар',
                'verbose_name_plural': 'Tовары',
            },
        ),
    ]
