# Generated by Django 3.2.4 on 2021-06-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_category'),
        ('item', '0002_auto_20210622_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_bestseller',
        ),
        migrations.AlterField(
            model_name='item',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='brand.brandcategory', verbose_name='Линейка'),
        ),
    ]
