# Generated by Django 3.2.4 on 2021-06-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_branditemline'),
        ('item', '0003_auto_20210623_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.AlterField(
            model_name='item',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='brand.branditemline', verbose_name='Линейка'),
        ),
    ]
