# Generated by Django 3.2.4 on 2021-07-01 18:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210623_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_text',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Цена текст'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
