# Generated by Django 3.2.4 on 2021-06-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_to_next_level',
            field=models.IntegerField(default=0),
        ),
    ]
