# Generated by Django 3.2.4 on 2021-06-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderstatus_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
    ]
